# Custom Language File for Launcher Customizer

[ejs.app]
title = "Leyo Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/LeYo77/Leyolauncher"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.com/users/725137670279397437"

[ejs.settings]
sourceGithubLink = "https://github.com/LeYo77/Leyolauncher"
supportLink = "https://github.com/LeYo77/Leyolauncher/issues"

[ejs.welcome]
welcomeHeader = "Bienvenue sur le serveur minecraft"
welcomeDescription = "Votre mission et de vous amuser."
welcomeDescCTA = "Vous n'êtes qu'à quelques clics du serveur."
